version: 2

jobs:
  build:
    working_directory: ~/build-test

    docker:
      - image: circleci/android:api-26-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "ViewFinderAnywhere/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "ViewFinderAnywhere/build.gradle" }}

      - run:
          name: Run Test
          command: ./gradlew test

      - run:
          name: Run Lint
          command: ./gradlew :ViewFinderAnywhere:lint

      - store_artifacts:
          path: ViewFinderAnywhere/build/reports
          destination: reports

      - store_test_results:
          path: ViewFinderAnywhere/build/reports

