version: 2.1

jobs:
  build_test_lint:
    docker:
      - image: cimg/android:2026.03.1-ndk

    working_directory: ~/project

    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx4g"

    steps:
      - checkout

      - run:
          name: Build
          command: ./gradlew assembleDebug

      - run:
          name: Test
          command: ./gradlew testDebug

      - run:
          name: Lint
          command: ./gradlew lintDebug

      - store_test_results:
          path: ViewFinderAnywhere/build/test-results

      - store_artifacts:
          path: ViewFinderAnywhere/build/reports

      - store_artifacts:
          path: ViewFinderAnywhere/build/outputs/apk/debug

workflows:
  ci:
    jobs:
      - build_test_lint

