version: 2.1

jobs:
  build_test_lint:
    docker:
      - image: cimg/android:2026.03.1-ndk

    working_directory: ~/project

    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx4g"

    steps:
      - checkout

      - run:
          name: Setup Env
          command: |
            yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - run:
          name: Build
          command: ./gradlew assembleDebug

      - run:
          name: Test
          command: ./gradlew testDebug

      - run:
          name: Lint
          command: ./gradlew lintDebug

      - store_test_results:
          path: .

      - store_artifacts:
          path: ViewFinderAnywhere/build/reports
          destination: reports_ViewFinderAnywhere

      - store_artifacts:
          path: ViewFinderAnywhere_UiPlugIn_Ingress/build/reports
          destination: reports_UiPlugIn_Ingress

      - store_artifacts:
          path: ViewFinderAnywhere_UiPlugIn_RedFrame/build/reports
          destination: reports_UiPlugIn_RedFrame

      - store_artifacts:
          path: ViewFinderAnywhere_UiPlugIn_TotalClear/build/reports
          destination: reports_UiPlugIn_TotalClear

      - store_artifacts:
          path: ViewFinderAnywhere/build/outputs/apk/debug
          destination: apk_ViewFinderAnywhere

      - store_artifacts:
          path: ViewFinderAnywhere_UiPlugIn_Ingress/build/outputs/apk/debug
          destination: apk_Ingress

      - store_artifacts:
          path: ViewFinderAnywhere_UiPlugIn_RedFrame/build/outputs/apk/debug
          destination: apk_RedFrame

      - store_artifacts:
          path: ViewFinderAnywhere_UiPlugIn_TotalClear/build/outputs/apk/debug
          destination: apk_TotalClear

workflows:
  ci:
    jobs:
      - build_test_lint

