apply plugin: 'com.android.application'

android {
    namespace 'com.fezrestia.android.viewfinderanywhere.uiplugin.redframe'

    compileSdk 36
    compileSdkMinor 1
    buildToolsVersion '36.1.0'

    defaultConfig {
        applicationId "com.fezrestia.android.viewfinderanywhere.uiplugin.redframe"
        minSdk 34
        targetSdk 36
        versionCode 102
        versionName '1.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
       }
    }

    androidComponents {
        onVariants(selector().withBuildType("release")) { variant ->
            variant.outputs.forEach { output ->
                def ver = output.versionName.orNull
                if (ver != null) {
                    def currentName = output.outputFileName.get()
                    def name = currentName.substring(0, currentName.lastIndexOf('.'))
                    name = name.replace("-release", "")
                    output.outputFileName.set("${name}_${ver}.apk")
                }
            }
        }
    }

    productFlavors {
    }
    lint {
        disable 'OldTargetApi', 'UnusedResources', 'IconDuplicates', 'IconMissingDensityFolder'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
